defmodule MobileAppBackend.PresentationStrings do
  use Gettext, backend: MobileAppBackend.Gettext

  alias MBTAV3API.Alert
  alias MBTAV3API.Route

  @spec route_type(Route.type(), boolean()) :: String.t()
  def route_type(:bus, true), do: gettext("bus")
  def route_type(:bus, false), do: gettext("buses")
  def route_type(:ferry, true), do: gettext("ferry")
  def route_type(:ferry, false), do: gettext("ferries")
  def route_type(_subway, true), do: gettext("train")
  def route_type(_subway, false), do: gettext("trains")

  @spec effect_sentence_case(Alert.effect()) :: String.t()
  def effect_sentence_case(effect) do
    case effect do
      :access_issue -> gettext("Access issue")
      :additional_service -> gettext("Additional service")
      :amber_alert -> gettext("Amber alert")
      :bike_issue -> gettext("Bike issue")
      :cancellation -> gettext("Trip cancelled")
      :delay -> gettext("Delay")
      :detour -> gettext("Detour")
      :dock_closure -> gettext("Dock closed")
      :dock_issue -> gettext("Dock issue")
      :elevator_closure -> gettext("Elevator closed")
      :escalator_closure -> gettext("Escalator closed")
      :extra_service -> gettext("Extra service")
      :facility_issue -> gettext("Facility issue")
      :modified_service -> gettext("Modified service")
      :no_service -> gettext("No service")
      :notice -> gettext("Notice")
      :parking_closure -> gettext("Parking closed")
      :parking_issue -> gettext("Parking issue")
      :policy_change -> gettext("Policy change")
      :schedule_change -> gettext("Schedule change")
      :service_change -> gettext("Service change")
      :shuttle -> gettext("Shuttle buses")
      :snow_route -> gettext("Snow route")
      :station_closure -> gettext("Station closed")
      :station_issue -> gettext("Station issue")
      :stop_closure -> gettext("Stop closed")
      :stop_move -> gettext("Stop moved")
      :stop_moved -> gettext("Stop moved")
      :stop_shoveling -> gettext("Stop shoveling")
      :summary -> gettext("Summary")
      :suspension -> gettext("Service suspended")
      :track_change -> gettext("Track change")
      :other_effect -> gettext("Alert")
      :unknown_effect -> gettext("Alert")
    end
  end

  @spec effect(Alert.effect()) :: String.t()
  def effect(effect) do
    case effect do
      :access_issue -> gettext("Access Issue")
      :additional_service -> gettext("Additional Service")
      :amber_alert -> gettext("Amber Alert")
      :bike_issue -> gettext("Bike Issue")
      :cancellation -> gettext("Cancellation")
      :delay -> gettext("Delay")
      :detour -> gettext("Detour")
      :dock_closure -> gettext("Dock Closure")
      :dock_issue -> gettext("Dock Issue")
      :elevator_closure -> gettext("Elevator Closure")
      :escalator_closure -> gettext("Escalator Closure")
      :extra_service -> gettext("Extra Service")
      :facility_issue -> gettext("Facility Issue")
      :modified_service -> gettext("Modified Service")
      :no_service -> gettext("No Service")
      :notice -> gettext("Notice")
      :parking_closure -> gettext("Parking Closure")
      :parking_issue -> gettext("Parking Issue")
      :policy_change -> gettext("Policy Change")
      :schedule_change -> gettext("Schedule Change")
      :service_change -> gettext("Service Change")
      :shuttle -> gettext("Shuttle")
      :snow_route -> gettext("Snow Route")
      :station_closure -> gettext("Station Closure")
      :station_issue -> gettext("Station Issue")
      :stop_closure -> gettext("Stop Closure")
      :stop_move -> gettext("Stop Moved")
      :stop_moved -> gettext("Stop Moved")
      :stop_shoveling -> gettext("Stop Shoveling")
      :summary -> gettext("Summary")
      :suspension -> gettext("Suspension")
      :trackChange -> gettext("Track Change")
      :other_effect -> gettext("Alert")
      :unknown_effect -> gettext("Alert")
    end
  end

  @spec cause_lower_case(Alert.cause()) :: String.t() | nil
  def cause_lower_case(cause) do
    case cause do
      :accident -> gettext("accident")
      :amtrak -> gettext("Amtrak")
      :amtrak_train_traffic -> gettext("Amtrak train traffic")
      :an_earlier_mechanical_problem -> gettext("an earlier mechanical problem")
      :an_earlier_signal_problem -> gettext("an earlier signal problem")
      :autos_impeding_service -> gettext("autos impeding service")
      :coast_guard_restriction -> gettext("Coast Guard restriction")
      :congestion -> gettext("congestion")
      :construction -> gettext("construction")
      :crossing_issue -> gettext("crossing issue")
      :crossing_malfunction -> gettext("crossing malfunction")
      :demonstration -> gettext("demonstration")
      :disabled_bus -> gettext("disabled bus")
      :disabled_train -> gettext("disabled train")
      :drawbridge_being_raised -> gettext("drawbridge being raised")
      :drawbridge_issue -> gettext("drawbridge issue")
      :electrical_work -> gettext("electrical work")
      :fire -> gettext("fire")
      :fire_department_activity -> gettext("fire department activity")
      :flooding -> gettext("flooding")
      :fog -> gettext("fog")
      :freight_train_interference -> gettext("freight train interference")
      :hazmat_condition -> gettext("hazmat condition")
      :heavy_ridership -> gettext("heavy ridership")
      :high_winds -> gettext("high winds")
      :holiday -> gettext("holiday")
      :hurricane -> gettext("hurricane")
      :ice_in_harbor -> gettext("ice in harbor")
      :maintenance -> gettext("maintenance")
      :mechanical_issue -> gettext("mechanical issue")
      :mechanical_problem -> gettext("mechanical problem")
      :medical_emergency -> gettext("medical emergency")
      :parade -> gettext("parade")
      :police_action -> gettext("police action")
      :police_activity -> gettext("police activity")
      :power_problem -> gettext("power problem")
      :rail_defect -> gettext("rail defect")
      :severe_weather -> gettext("severe weather")
      :signal_issue -> gettext("signal issue")
      :signal_problem -> gettext("signal problem")
      :single_tracking -> gettext("single tracking")
      :slippery_rail -> gettext("slippery rail")
      :snow -> gettext("snow")
      :special_event -> gettext("special event")
      :speed_restriction -> gettext("speed restriction")
      :strike -> gettext("strike")
      :switch_issue -> gettext("switch issue")
      :switch_problem -> gettext("switch problem")
      :technical_problem -> gettext("technical problem")
      :tie_replacement -> gettext("tie replacement")
      :track_problem -> gettext("track problem")
      :track_work -> gettext("track work")
      :traffic -> gettext("traffic")
      :train_traffic -> gettext("train traffic")
      :unruly_passenger -> gettext("unruly passenger")
      :weather -> gettext("weather")
      _ -> nil
    end
  end

  @spec cause(Alert.cause()) :: String.t() | nil
  def cause(cause) do
    case cause do
      :accident -> gettext("Accident")
      :amtrak -> gettext("Amtrak")
      :amtrak_train_traffic -> gettext("Amtrak Train Traffic")
      :an_earlier_mechanical_problem -> gettext("An Earlier Mechanical Problem")
      :an_earlier_signal_problem -> gettext("An Earlier Signal Problem")
      :autos_impeding_service -> gettext("Autos Impeding Service")
      :coast_guard_restriction -> gettext("Coast Guard Restriction")
      :congestion -> gettext("Congestion")
      :construction -> gettext("Construction")
      :crossing_issue -> gettext("Crossing Issue")
      :crossing_malfunction -> gettext("Crossing Malfunction")
      :demonstration -> gettext("Demonstration")
      :disabled_bus -> gettext("Disabled Bus")
      :disabled_train -> gettext("Disabled Train")
      :drawbridge_being_raised -> gettext("Drawbridge Being Raised")
      :drawbridge_issue -> gettext("Drawbridge Issue")
      :electrical_work -> gettext("Electrical Work")
      :fire -> gettext("Fire")
      :fire_department_activity -> gettext("Fire Department Activity")
      :flooding -> gettext("Flooding")
      :fog -> gettext("Fog")
      :freight_train_interference -> gettext("Freight Train Interference")
      :hazmat_condition -> gettext("Hazmat Condition")
      :heavy_ridership -> gettext("Heavy Ridership")
      :high_winds -> gettext("High Winds")
      :holiday -> gettext("Holiday")
      :hurricane -> gettext("Hurricane")
      :ice_in_harbor -> gettext("Ice In Harbor")
      :maintenance -> gettext("Maintenance")
      :mechanical_issue -> gettext("Mechanical Issue")
      :mechanical_problem -> gettext("Mechanical Problem")
      :medical_emergency -> gettext("Medical Emergency")
      :parade -> gettext("Parade")
      :police_action -> gettext("Police Action")
      :police_activity -> gettext("Police Activity")
      :power_problem -> gettext("Power Problem")
      :rail_defect -> gettext("Rail Defect")
      :severe_weather -> gettext("Severe Weather")
      :signal_issue -> gettext("Signal Issue")
      :signal_problem -> gettext("Signal Problem")
      :single_tracking -> gettext("Single Tracking")
      :slippery_rail -> gettext("Slippery Rail")
      :snow -> gettext("Snow")
      :special_event -> gettext("Special Event")
      :speed_restriction -> gettext("Speed Restriction")
      :strike -> gettext("Strike")
      :switch_issue -> gettext("Switch Issue")
      :switch_problem -> gettext("Switch Problem")
      :technical_problem -> gettext("Technical Problem")
      :tie_replacement -> gettext("Tie Replacement")
      :track_problem -> gettext("Track Problem")
      :track_work -> gettext("Track Work")
      :traffic -> gettext("Traffic")
      :train_traffic -> gettext("Train Traffic")
      :unruly_passenger -> gettext("Unruly Passenger")
      :weather -> gettext("Weather")
      _ -> nil
    end
  end
end
