name: Deploy to Dev-Orange

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy ${{ github.ref_type }} ${{ github.ref_name }} to Dev-Orange
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev-orange
    secrets: inherit
