on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      version-name:
        required: false
        type: string
      deploy-desc:
        required: true
        type: string
        description: A description of what was deployed ("branch main", "PR 483", "tag 2023-11-15-1", etc)
    secrets:
      AWS_ROLE_ARN:
        required: true
      DOCKER_REPO:
        required: true
      SLACK_WEBHOOK:
        required: true

concurrency:
  group: deploy-${{ inputs.env }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.env }}
    steps:
      - uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get versions
        id: calc-version
        run: |
          git_hash_tag="${{ secrets.DOCKER_REPO }}:git-$(git rev-parse --short HEAD)"
          latest_env_tag="${{ secrets.DOCKER_REPO }}:latest-${INPUTS_ENV}"
          if [ -n "${INPUTS_VERSION_NAME}" ]; then
            version_tag="${{ secrets.DOCKER_REPO }}:${INPUTS_VERSION_NAME}"
            echo "deploy-tag=$version_tag" | tee -a $GITHUB_OUTPUT
            printf "tag-list=%s,%s,%s\n" "$git_hash_tag" "$latest_env_tag" "$version_tag" | tee -a $GITHUB_OUTPUT
          else
            echo "deploy-tag=$git_hash_tag" | tee -a $GITHUB_OUTPUT
            printf "tag-list=%s,%s\n" "$git_hash_tag" "$latest_env_tag" | tee -a $GITHUB_OUTPUT
          fi
        env:
          INPUTS_ENV: ${{ inputs.env }}
          INPUTS_VERSION_NAME: ${{ inputs.version-name }}
      - uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          cache-from: type=gha
          tags: ${{ steps.calc-version.outputs.tag-list }}
          push: true
      - uses: mbta/actions/deploy-ecs@d37877022d4ae12e96663d2e0a970a5214a2e232 # v2.20
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          ecs-cluster: mobile-app-backend
          ecs-service: mobile-app-backend-${{ inputs.env }}
          docker-tag: ${{ steps.calc-version.outputs.deploy-tag }}
      - uses: mbta/actions/notify-slack-deploy@d37877022d4ae12e96663d2e0a970a5214a2e232 # v2.20
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
          custom-message: Deployed ${{ inputs.deploy-desc }} to ${{ inputs.env }}
