name: Deploy to Dev-Orange

on:
  workflow_dispatch:
  push:
    branches: [main, mth-deploy]

jobs:
  deploy:
    name: Deploy ${{ github.ref }} to Dev-Orange
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev-orange
    secrets: inherit
