name: Deploy to Staging
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Deploy {0} {1} to Staging', github.ref_type, github.ref_name) || '' }}

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: {}

jobs:
  deploy:
    name: Deploy ${{ github.ref_type }} ${{ github.ref_name }} to Staging
    uses: ./.github/workflows/deploy.yml
    with:
      env: staging
      deploy-desc: ${{ github.ref_type }} ${{ github.ref_name }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
