name: Deploy to Staging

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy ${{ github.ref }} to Staging
    uses: ./.github/workflows/deploy.yml
    with:
      env: staging
    secrets: inherit
