on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      version-name:
        required: false
        type: string
      deploy-desc:
        required: true
        type: string
        description: A description of what was deployed ("branch main", "PR 483", "tag 2023-11-15-1", etc)
    secrets:
      AWS_ROLE_ARN:
        required: true
      DOCKER_REPO:
        required: true
      SLACK_WEBHOOK:
        required: true

concurrency:
  group: deploy-${{ inputs.env }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: build-push
        uses: mbta/actions/build-push-ecr@mth-docker-build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
          docker-additional-tags: |
            type=raw,value=latest-${{ inputs.env }}
            type=raw,enable=${{ inputs.version-name != '' }},priority=1100,value=${{ inputs.version-name }}
      - uses: mbta/actions/deploy-ecs@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          ecs-cluster: mobile-app-backend
          ecs-service: mobile-app-backend-${{ inputs.env }}
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
      - uses: mbta/actions/notify-slack-deploy@v2
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
          custom-message: Deployed ${{ inputs.deploy-desc }} to ${{ inputs.env }}
