name: Deploy to Prod
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Deploy {0} {1} to Prod', github.ref_type, github.ref_name) || '' }}

on:
  release:
    types:
      - released
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    name: Deploy ${{ github.ref_type }} ${{ github.ref_name }} to Prod
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      env: prod
      deploy-desc: ${{ github.ref_type }} ${{ github.ref_name }}
      version-name: ${{ github.ref_name }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
