name: Deploy to Dev-Orange

on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - labeled

jobs:
  deploy:
    name: Deploy ${{ github.ref_type }} ${{ github.ref_name }} to Dev-Orange
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'deploy to dev-orange') }}
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev-orange
    secrets: inherit
