name: Deploy to Staging
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Deploy {0} {1} to Staging', github.ref_type, github.ref_name) || '' }}

on:
  workflow_dispatch:
    inputs:
      release-name:
        description: The name to use for the created release
        type: string
        required: false
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy ${{ github.ref_type }} ${{ github.ref_name }} to Staging
    uses: ./.github/workflows/deploy.yml
    with:
      env: staging
      version-name: ${{ inputs.release-name }}
      deploy-desc: ${{ github.ref_type }} ${{ github.ref_name }}
    secrets: inherit
